[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
